### ISSUE TITLE
Image Captioning Does Not Work?

### ISSUE THREAD

**Issue by PaulFidika** [SOELexicon/ComfyUI-LexTools#2]
Could you share any example workflows; I might be doing this wrong. But I'm taking LoadImage -> ImageCaptioning -> ShowText, and the image-captioning node is throwing an error, regardless of the image used:

```
Error occurred when executing ImageCaptioning:

Cannot handle this data type: (1, 1, 1023), |u1
```

Am I supposed to format the image in some way prior to feeding it into the caption node? Thanks.

**Comment by SOELexicon** [comment]
i think i see the issue working on a fix

**Comment by SOELexicon** [comment]
> Could you share any example workflows; I might be doing this wrong. But I'm taking LoadImage -> ImageCaptioning -> ShowText, and the image-captioning node is throwing an error, regardless of the image used:
> 
> ```
> Error occurred when executing ImageCaptioning:
> 
> Cannot handle this data type: (1, 1, 1023), |u1
> ```
> 
> Am I supposed to format the image in some way prior to feeding it into the caption node? Thanks.

should be fixed in latest pull
